apiVersion: apps/v1
kind: Deployment
metadata:
  name: wso2ei
  namespace: develop
spec:
  selector:
    matchLabels:
      app: wso2ei
  template:
    metadata:
      labels:
        app: wso2ei
    spec:
      nodeSelector:
        nombre: dev2
      containers:
      - image: wso2ei:2
        name: wso2ei
        resources:
          requests:
            memory: 2Gi
            cpu: "1"
          limits:
            memory: 4Gi
            cpu: "2"
        env:
        - name: DB_USER
          value: wso2carbon
        - name: DB_PASSWORD
          value: zbCmQfp7nmuvFaxF
        - name: DB_NAME
          value: wso2carbon_db
        volumeMounts:
        - name: wso2ei-logs-pv-storage
          mountPath: /opt/wso2/wso2ei-6.6.0/repository/logs
        ports:
        - containerPort: 8280
          name: port1
        - containerPort: 8243
          name: port2
        - containerPort: 9443
          name: port3
        - containerPort: 4100
          name: port4
      volumes:   
      - name: wso2ei-logs-pv-storage
        persistentVolumeClaim:
          claimName: wso2ei-logs-pv-claim
      
