apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-qa-volume
  namespace: calidad
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nombre
          operator: In
          values:
          - qa2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-qa-claim
  namespace: calidad
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
