apiVersion: v1
kind: Service
metadata:
    name: wso2ie-lb-qa
    namespace: calidad
spec:
  selector:
    app: wso2ei
  ports:
   - port: 9443
     targetPort: 9443 
     name: port1
   - port: 8280
     targetPort: 8280
     name: port2
   - port: 8243
     targetPort: 8243
     name: port3
   - port: 7963 
     targetPort: 7693
     name: port4
  type: LoadBalancer
